"""Agent C -- functional principle synthesizer.

When Ob's composite score >= target, Agent C crystallises the converged
rule into an explicit, reusable principle.  The synthesised output has
two complementary pieces:

  1. A *fitted approximant*  f(n) = theta^{-1}((n-a) pi)
                                   + sum_k c_k P_k(u(n))
                                   + spline(n).
     Fast, closed-form, accurate to whatever RMSE the loop converged to.

  2. The *exact mathematical principle*: gamma_n is the n-th positive
     root of the Hardy Z-function, Z(t) = e^{i theta(t)} zeta(1/2 + i t).
     The synthesiser embeds a Z-bisection refinement using the local
     `find_zero_near` helper so callers can obtain any zero to machine
     precision with the fitted approximant as seed.

Honest scope
------------
This module does *not* prove RH.  The principle it names is the classical
Riemann-Siegel / Hardy characterisation, which is equivalent to the
statement "all non-trivial zeta zeros on Re(s)=1/2 are roots of Z".
"""
from __future__ import annotations

import numpy as np

from riemann.core.riemann_siegel import find_zero_near

from ..agent_a.extractor import parse_offset_a
from ..core.schemas import (
    ConvergenceReport,
    FunctionalPrinciple,
    ZeroDataset,
    ZeroRule,
)


_FUNCTION_TEMPLATE = '''\
"""Generator for the n-th non-trivial zero of the Riemann zeta function.

Auto-generated by Opensens Academic Explorer :: riemann.agent_c.

Training summary:
    fitted on  : {n_fit} zeros (LMFDB / Odlyzko zeros1)
    match_rate : {match_rate:.6f}
    RMSE       : {rmse:.4e}
    median rel : {rel:.4e}
    offset  a  : {offset_a!r}
    #coeffs k  : {n_coeffs}
    #knots     : {n_knots}

Functional principle (exact):
    Let   theta(t) = Im log Gamma(1/4 + i t / 2) - (t / 2) log pi,
          Z(t)     = exp(i theta(t)) * zeta(1/2 + i t)   [real for real t].
    Then gamma_n is the n-th positive root of Z(t).
"""
import numpy as np
from scipy.special import loggamma, lambertw


_OFFSET_A  = {offset_a!r}
_COEFFS    = np.array({coeffs!r}, dtype=np.float64)
_KNOTS_N   = np.array({knots_n!r}, dtype=np.float64)
_KNOTS_R   = np.array({knots_r!r}, dtype=np.float64)
_N_TRAIN   = {n_fit}


def _theta(t):
    return np.imag(loggamma(0.25 + 0.5j * t)) - 0.5 * t * np.log(np.pi)


def _theta_inverse(target):
    target = np.asarray(target, dtype=np.float64)
    x = target / np.pi + 1.0
    w = np.real(lambertw(np.maximum(x / np.e, 1e-6)))
    t = 2 * np.pi * np.maximum(x, 0.5) / np.maximum(w, 1e-6)
    t = np.maximum(t, 10.0)
    for _ in range(80):
        f = _theta(t) - target
        fp = np.maximum(0.5 * np.log(t / (2 * np.pi)) - 1.0 / (24 * t * t), 1e-6)
        step = f / fp
        step = np.clip(step, -0.5 * np.abs(t) - 1.0, 0.5 * np.abs(t) + 1.0)
        t = t - step
        if np.max(np.abs(f)) < 1e-12:
            break
    return t


def _legendre_basis(n, n_total, k):
    if k <= 0:
        return np.zeros((n.size, 0))
    u = 2.0 * (n - 1.0) / max(n_total - 1, 1) - 1.0
    p_prev = np.ones_like(u)
    p_curr = u.copy()
    cols = [p_curr / np.sqrt(2.0 / 3.0)]
    for l in range(1, k):
        p_next = ((2 * l + 1) * u * p_curr - l * p_prev) / (l + 1)
        p_prev, p_curr = p_curr, p_next
        cols.append(p_curr / np.sqrt(2.0 / (2 * (l + 1) + 1)))
    return np.column_stack(cols)


def riemann_zero_approx(n):
    """Fitted approximant -- fast and closed-form (no mpmath)."""
    n_arr = np.atleast_1d(np.asarray(n, dtype=np.float64))
    t = _theta_inverse(np.pi * (n_arr - _OFFSET_A))
    if _COEFFS.size:
        X = _legendre_basis(n_arr, _N_TRAIN, _COEFFS.size)
        t = t + X @ _COEFFS
    if _KNOTS_N.size >= 2:
        t = t + np.interp(n_arr, _KNOTS_N, _KNOTS_R)
    return float(t[0]) if np.asarray(n).ndim == 0 else t


def riemann_zero(n, refine=True, tol=1e-10):
    """Return gamma_n.  When `refine=True` (default) the result is
    polished by bisecting the Hardy Z-function around the approximant;
    this uses the local sign-change bisection helper and yields
    machine-precision zeros.
    """
    approx = riemann_zero_approx(n)
    if not refine:
        return approx
    def _one(seed):
        gamma, _, _ = find_zero_near(float(seed), tol=tol)
        return float(gamma)
    if np.isscalar(n) or np.asarray(n).ndim == 0:
        return _one(approx)
    return np.array([_one(s) for s in np.atleast_1d(approx)], dtype=np.float64)


if __name__ == "__main__":
    print("gamma_1 approx  :", riemann_zero_approx(1))
    print("gamma_1 refined :", riemann_zero(1))
    print("gamma_10 approx :", riemann_zero_approx(10))
    print("gamma_10 refined:", riemann_zero(10))
'''


def synthesize(
    rule: ZeroRule,
    dataset: ZeroDataset,
    final_report: ConvergenceReport,
) -> FunctionalPrinciple:
    offset_a = parse_offset_a(rule)
    src = _FUNCTION_TEMPLATE.format(
        n_fit=rule.fitted_on_n_zeros,
        match_rate=final_report.components.match_rate,
        rmse=final_report.components.rmse,
        rel=final_report.components.rel_error_median,
        offset_a=float(offset_a),
        n_coeffs=int(rule.correction_coeffs.size),
        n_knots=int(rule.spline_knots_n.size),
        coeffs=rule.correction_coeffs.tolist(),
        knots_n=rule.spline_knots_n.tolist(),
        knots_r=rule.spline_knots_r.tolist(),
    )

    params = {
        "offset_a": float(offset_a),
        "correction_coeffs": rule.correction_coeffs.tolist(),
        "spline_knots_n": rule.spline_knots_n.tolist(),
        "spline_knots_r": rule.spline_knots_r.tolist(),
        "n_training_zeros": int(rule.fitted_on_n_zeros),
    }

    description = (
        "Exact principle: gamma_n is the n-th positive root of the Hardy "
        "Z-function Z(t) = e^{i theta(t)} zeta(1/2 + i t), where "
        "theta(t) = Im log Gamma(1/4 + i t / 2) - (t/2) log pi.  "
        "Fitted approximant: gamma_n ~ theta^{-1}((n - a) pi) + "
        "sum_k c_k P_k(u(n)) + spline(n), with P_k the normalised "
        "Legendre basis on the training window and spline(n) a binned "
        "residual capturing the Riemann-Siegel S(gamma) fluctuations."
    )

    return FunctionalPrinciple(
        name="riemann_zero_hardy_Z_v1",
        description=description,
        parameters=params,
        python_callable_src=src,
        validation_rmse=final_report.components.rmse,
        validation_match_rate=final_report.components.match_rate,
        notes=(
            "Output emits both a fitted approximant (closed-form, instant) "
            "and a Z-bisection refinement (via find_zero_near) that returns "
            "machine-precision zeros for any n, inside or outside the "
            f"training window of {rule.fitted_on_n_zeros} zeros."
        ),
    )


class AgentC:
    name = "C"
    role = "Functional Principle Synthesizer"

    def run(
        self,
        rule: ZeroRule,
        dataset: ZeroDataset,
        final_report: ConvergenceReport,
    ) -> FunctionalPrinciple:
        return synthesize(rule, dataset, final_report)
